name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [14,18,24]
                operational-system: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 20
                      operational-system: ubuntu-latest
                exclude:
                    - node-version: [14,18]
                      operational-system: windows-latest
        runs-on: ${{ matrix.operational-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Depends
              run: npm ci
            - name: Build project
              run: npm run build
